services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: portofolio-ai-backend:latest
    container_name: portofolio-ai-backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - ENVIRONMENT=production
      - POSTGRES_SERVER=db
    volumes:
      - ./static/faiss_index:/app/static/faiss_index
      - ./audio:/app/audio
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    container_name: portofolio-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: