services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-ai-backend:latest
    container_name: portfolio-ai-backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - ENVIRONMENT=production
    volumes:
      - ./database.db:/app/database.db
      - ./static/faiss_index:/app/static/faiss_index
    restart: unless-stopped